{
 "title": "Closed AI App Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(users_total) - sum(users_deleted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Projects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(projects_total) - sum(projects_deleted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tasks_total) - sum(tasks_deleted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "sum(tasks_deleted_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "sum(tasks_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Projects created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "sum(projects_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Projects Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "sum(projects_deleted_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "sum(users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "sum(users_deleted_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}