services:
  traefik:
    image: traefik:v3.4.1
    container_name: traefik
    ports:
      - "80:80"    # HTTP entrypoint
      - "8080:8080"  # dashboard (insecure)
    command:
      - --api.insecure=true
      - --providers.docker=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  project-service:
    build:
      context: ./server
      dockerfile: project-service/Dockerfile
    expose:
      - "8083"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=PathPrefix(`/projects`)"
      - "traefik.http.services.project.loadbalancer.server.port=8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/closedai
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  user-service:
    build:
      context: ./server
      dockerfile: user-service/Dockerfile
    expose:
      - "8082"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/users`)"
      - "traefik.http.services.user.loadbalancer.server.port=8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/closedai
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  task-service:
    build:
      context: ./server
      dockerfile: task-service/Dockerfile
    expose:
      - "8081"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.task.rule=PathPrefix(`/tasks`)"
      - "traefik.http.services.task.loadbalancer.server.port=8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/closedai
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=closedai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  genai:
    build:
      context: ./genai
      dockerfile: Dockerfile
    env_file:
      - ./genai/.env
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.genai.rule=PathPrefix(`/genai`)"
      - "traefik.http.services.genai.loadbalancer.server.port=8000"

volumes:
  postgres_data:
