services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - ./genai/.env
    volumes:
      - ollama_data:/ollama_data
      - ./genai/ollama-setup.sh:/ollama-setup.sh
    entrypoint: [ "/bin/bash", "-c", "/ollama-setup.sh" ]

  genai:
    depends_on:
      - ollama

volumes:
  ollama_data:
