services:
  recommender-service:
    build:
      context: ./recommender-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  ollama-service:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - ollama-data:/ollama_data
      - ./ollama-setup.sh:/ollama-setup.sh
    entrypoint: [ "/bin/bash", "-c", "/ollama-setup.sh" ]
    deploy:
      replicas: ${LOCAL_LLM:-false}
    profiles:
      - local-llm

volumes:
  ollama-data:
