global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "project-service"
    static_configs:
      - targets: ["project-service:8083"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s

  - job_name: "task-service"
    static_configs:
      - targets: ["task-service:8081"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8082"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 30s

  - job_name: "genai-service"
    static_configs:
      - targets: ["genai:8084"]
    metrics_path: "/metrics"
    scrape_interval: 30s
