# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_add_task_to_project(self) -> None:
        """Test case for add_task_to_project

        Add a task to a project
        """
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Create a new project
        """
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete a project
        """
        pass

    def test_get_all_projects(self) -> None:
        """Test case for get_all_projects

        Get all projects
        """
        pass

    def test_get_project_by_id(self) -> None:
        """Test case for get_project_by_id

        Get a project by ID
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
