@startuml Use_Case_Diagram
left to right direction
skinparam packageStyle rectangle

actor User

rectangle "Closed AI" {
    User --> (Create Task)
    User --> (Create Project)
    User --> (Chat with AI)

    (Create Task) ..> (Edit Task Description) : <<include>>
    (Create Task) ..> (Update Status) : <<include>>
    (Create Task) ..> (Assign User) : <<include>>
    (Create Task) ..> (Edit Title) : <<include>>

    (Create Project) ..> (Edit Project Description) : <<include>>
    (Create Project) ..> (Edit Name) : <<include>>

    (Chat with AI) ..> (Accept Task Recommendatios) : <<include>>
    (Chat with AI) ..> (Reject Task Recommendations) : <<include>>
}

@enduml
