# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from server_api.models.task_dto import TaskDto

class TestTaskDto(unittest.TestCase):
    """TaskDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskDto:
        """Test TaskDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskDto`
        """
        model = TaskDto()
        if include_optional:
            return TaskDto(
                id = 56,
                title = '',
                description = '',
                task_status = 'OPEN',
                comments = [
                    ''
                    ],
                attachments = [
                    ''
                    ],
                assignee_id = 56
            )
        else:
            return TaskDto(
                id = 56,
                title = '',
                description = '',
                task_status = 'OPEN',
                comments = [
                    ''
                    ],
                attachments = [
                    ''
                    ],
        )
        """

    def testTaskDto(self):
        """Test TaskDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
