# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from server_api.api.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_change_task_status(self) -> None:
        """Test case for change_task_status

        Change the status of a task
        """
        pass

    def test_delete_task(self) -> None:
        """Test case for delete_task

        Delete a task
        """
        pass

    def test_get_all_tasks(self) -> None:
        """Test case for get_all_tasks

        Get all tasks
        """
        pass

    def test_get_task_by_id(self) -> None:
        """Test case for get_task_by_id

        Get a task by ID
        """
        pass

    def test_get_tasks_by_assignee(self) -> None:
        """Test case for get_tasks_by_assignee

        Get tasks by assignee
        """
        pass

    def test_get_tasks_by_project(self) -> None:
        """Test case for get_tasks_by_project

        Get tasks by project
        """
        pass

    def test_update_task(self) -> None:
        """Test case for update_task

        Update a task
        """
        pass


if __name__ == '__main__':
    unittest.main()
