# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from server_api.models.user_dto import UserDto

class TestUserDto(unittest.TestCase):
    """UserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserDto:
        """Test UserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserDto`
        """
        model = UserDto()
        if include_optional:
            return UserDto(
                id = 56,
                name = '',
                profile_picture = ''
            )
        else:
            return UserDto(
                id = 56,
                name = '',
                profile_picture = '',
        )
        """

    def testUserDto(self):
        """Test UserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
