# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_user_dto import CreateUserDto

class TestCreateUserDto(unittest.TestCase):
    """CreateUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUserDto:
        """Test CreateUserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserDto`
        """
        model = CreateUserDto()
        if include_optional:
            return CreateUserDto(
                name = '',
                profile_picture = ''
            )
        else:
            return CreateUserDto(
                name = '',
        )
        """

    def testCreateUserDto(self):
        """Test CreateUserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
