# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_project_dto import CreateProjectDto

class TestCreateProjectDto(unittest.TestCase):
    """CreateProjectDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProjectDto:
        """Test CreateProjectDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProjectDto`
        """
        model = CreateProjectDto()
        if include_optional:
            return CreateProjectDto(
                name = '',
                color = ''
            )
        else:
            return CreateProjectDto(
                name = '',
                color = '',
        )
        """

    def testCreateProjectDto(self):
        """Test CreateProjectDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
