# coding: utf-8

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.add_task_dto import AddTaskDto

class TestAddTaskDto(unittest.TestCase):
    """AddTaskDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddTaskDto:
        """Test AddTaskDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddTaskDto`
        """
        model = AddTaskDto()
        if include_optional:
            return AddTaskDto(
                title = '',
                description = ''
            )
        else:
            return AddTaskDto(
                title = '',
                description = '',
        )
        """

    def testAddTaskDto(self):
        """Test AddTaskDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
