# coding: utf-8

"""
DevOps Closed AI Server API

API documentation for the DevOps Closed AI Server

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create a new user
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user
        """
        pass

    def test_get_all_users(self) -> None:
        """Test case for get_all_users

        Get all users
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Get a user by ID
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update a user
        """
        pass


if __name__ == "__main__":
    unittest.main()
