namespace: closed-ai

# Global settings
global:
  postgresql:
    auth:
      username: postgres
      password: postgres
      database: closedai

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Services configuration
services:
  project:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/project-service
      tag: latest
    port: 8083
    path: /projects

  user:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/user-service
      tag: latest
    port: 8082
    path: /users

  task:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/task-service
      tag: latest
    port: 8081
    path: /tasks

  client:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/client
      tag: latest
    port: 3000
    path: /

  genai:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/genai-service
      tag: latest
    port: 8084
    path: /interpret

vectorizer:
  enabled: true
  image:
    repository: timescale/pgai-vectorizer-worker
    tag: latest

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
  port: 11434

pgvector:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: closedai
  image:
    repository: pgvector/pgvector
    tag: "pg16"
  persistence:
    enabled: true
    size: 2Gi

# Monitoring configuration
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v3.5.0
  port: 9090
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    enabled: true
    size: 8Gi
  rbac:
    create: true
    namespaced: true  # Restrict to current namespace only
  alertmanager:
    enabled: true
    port: 9093
  config:
    scrape_interval: 15s
    evaluation_interval: 15s

grafana:
  path: /grafana
  enabled: true
  image:
    repository: grafana/grafana
    tag: 12.0.2
  port: 3000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
  auth:
    disable_login: true
    disable_basic_auth: true
  anonymous:
    enabled: true
    org_role: Admin
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true
  dashboardProviders:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
        foldersFromFilesStructure: true
