namespace: closed-ai

# Global settings
global:
  postgresql:
    auth:
      username: postgres
      password: postgres
      database: closedai

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Services configuration
services:
  project:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/project-service
      tag: latest
    port: 8083
    path: /projects

  user:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/user-service
      tag: latest
    port: 8082
    path: /users

  task:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/task-service
      tag: latest
    port: 8081
    path: /tasks

  client:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/client
      tag: latest
    port: 3000
    path: /

  genai:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/genai-service
      tag: latest
    port: 8084
    path: /interpret

vectorizer:
  enabled: true
  image:
    repository: timescale/pgai-vectorizer-worker
    tag: latest

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
  port: 11434

pgvector:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: closedai
  image:
    repository: pgvector/pgvector
    tag: "pg16"
  persistence:
    enabled: true
    size: 2Gi

# Monitoring configuration
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v3.5.0
  port: 9090
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    enabled: true
    size: 8Gi
  rbac:
    create: true
    namespaced: true  # Restrict to current namespace only
  alertmanager:
    enabled: true
    port: 9093
  config:
    scrape_interval: 15s
    evaluation_interval: 15s

grafana:
  path: /grafana
  enabled: true
  image:
    repository: grafana/grafana
    tag: 12.0.2
  port: 3000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
  auth:
    disable_login: true
    disable_basic_auth: true
  anonymous:
    enabled: true
    org_role: Admin
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true
  dashboardProviders:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
        foldersFromFilesStructure: true
  alerting:
    contactPoints:
      webhookUrl: 'SET WEBHOOK URL HERE'
    alertRules:
      groups:
        - orgId: 1
          name: GenAI Usage
          folder: GenAI
          interval: 1m
          rules:
            - uid: ceshspmbrclq8a
              title: Total GenAI Requests
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 3600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    adhocFilters: []
                    datasource:
                      type: prometheus
                      uid: prometheus
                    editorMode: code
                    expr: sum(increase(genai_answering_tasks_total[24h])) + sum(increase(genai_generation_tasks_total[24h]))
                    instant: true
                    interval: ""
                    intervalMs: 15000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                      - evaluator:
                          params:
                            - 20
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                            - C
                        reducer:
                          params: []
                          type: last
                        type: query
                    datasource:
                      type: __expr__
                      uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              dashboardUid: 84e033ec-d6c2-48a9-ae26-d336dd6c7053
              panelId: 15
              noDataState: NoData
              execErrState: Error
              annotations:
                __dashboardUid__: 84e033ec-d6c2-48a9-ae26-d336dd6c7053
                __panelId__: "15"
                description: Gen AI Usage has surpassed 20 requests in Total in the last 24 hours, make sure this is within limits defined.
                summary: Gen AI Usage has surpassed 20 requests in Total.
              isPaused: false
              notification_settings:
                receiver: Closed AI Discord k8s

