namespace: closed-ai

# Global settings
global:
  postgresql:
    auth:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_NAME}

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Services configuration
services:
  project:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/project-service
      tag: latest
    port: 8083
    path: /projects

  user:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/user-service
      tag: latest
    port: 8082
    path: /users

  task:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/task-service
      tag: latest
    port: 8081
    path: /tasks

  client:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/client
      tag: latest
    port: 3000
    path: /

  genai:
    enabled: true
    image:
      repository: ghcr.io/aet-devops25/team-closed-ai/genai-service
      tag: latest
    port: 8084
    path: /genai

  ollama:
    enabled: false
    image:
      repository: ollama/ollama
      tag: latest
    port: 11434

  vectorizer:
    enabled: true
    image:
      repository: timescale/pgai-vectorizer-worker
      tag: latest

pgvector:
  enabled: true
  auth:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
  image:
    repository: pgvector/pgvector
    tag: "pg16"
  persistence:
    enabled: true
    size: 2Gi
