# coding: utf-8

# flake8: noqa

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ProjectApi",
    "TaskApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddTaskDto",
    "CreateProjectDto",
    "ProjectDto",
    "TaskDto",
    "TaskStatus",
    "UserDto",
]

# import apis into sdk package
from server_api.api.project_api import ProjectApi as ProjectApi
from server_api.api.task_api import TaskApi as TaskApi
from server_api.api.user_api import UserApi as UserApi

# import ApiClient
from server_api.api_response import ApiResponse as ApiResponse
from server_api.api_client import ApiClient as ApiClient
from server_api.configuration import Configuration as Configuration
from server_api.exceptions import OpenApiException as OpenApiException
from server_api.exceptions import ApiTypeError as ApiTypeError
from server_api.exceptions import ApiValueError as ApiValueError
from server_api.exceptions import ApiKeyError as ApiKeyError
from server_api.exceptions import ApiAttributeError as ApiAttributeError
from server_api.exceptions import ApiException as ApiException

# import models into sdk package
from server_api.models.add_task_dto import AddTaskDto as AddTaskDto
from server_api.models.create_project_dto import CreateProjectDto as CreateProjectDto
from server_api.models.project_dto import ProjectDto as ProjectDto
from server_api.models.task_dto import TaskDto as TaskDto
from server_api.models.task_status import TaskStatus as TaskStatus
from server_api.models.user_dto import UserDto as UserDto
