# coding: utf-8

# flake8: noqa

"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ProjectApi",
    "TaskApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddTaskDto",
    "CreateProjectDto",
    "CreateUserDto",
    "ProjectDto",
    "TaskDto",
    "TaskStatus",
    "UserDto",
]

# import apis into sdk package
from openapi_client.api.project_api import ProjectApi as ProjectApi
from openapi_client.api.task_api import TaskApi as TaskApi
from openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_task_dto import AddTaskDto as AddTaskDto
from openapi_client.models.create_project_dto import CreateProjectDto as CreateProjectDto
from openapi_client.models.create_user_dto import CreateUserDto as CreateUserDto
from openapi_client.models.project_dto import ProjectDto as ProjectDto
from openapi_client.models.task_dto import TaskDto as TaskDto
from openapi_client.models.task_status import TaskStatus as TaskStatus
from openapi_client.models.user_dto import UserDto as UserDto
