apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ $.Values.namespace }}
data:
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.global.postgresql.auth.database }}
  SPRING_PROFILES_ACTIVE: "shared,shared-k8s"

  VITE_API_URL: 'https://closed-ai.student.k8s.aet.cit.tum.de/'

  # Ollama LLM configuration for genai
  OLLAMA_LLM_HOST: "https://gpu.aet.cit.tum.de/ollama"

  # LLM models to use for different tasks
  CLASSIFICATION_MODEL: "gemma3:4b"
  ANSWER_MODEL: "llama3.3:latest"
  TASK_GEN_MODEL: "llama3.3:latest"

  # Ollama embedding configuration
  OLLAMA_EMBED_HOST: "https://gpu.aet.cit.tum.de/ollama"
  EMBED_MODEL: "nomic-embed-text"
  EMBED_DIMENSIONS: "768"

  # PostgreSQL database configuration for genai
  PG_HOST: "{{ .Release.Name }}-postgres"
  PG_PORT: "5432"
  DATABASE_URL: "postgres://{{ .Values.global.postgresql.auth.username }}:{{ .Values.global.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.global.postgresql.auth.database }}"

  # Ollama vectorizer worker configuration
  OLLAMA_HOST: "https://gpu.aet.cit.tum.de/ollama"
  PGAI_VECTORIZER_WORKER_DB_URL: "postgres://{{ .Values.global.postgresql.auth.username }}:{{ .Values.global.postgresql.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.global.postgresql.auth.database }}"

  TRAEFIK_URL: 'https://closed-ai.student.k8s.aet.cit.tum.de/'