{{- range $service, $config := .Values.services }}
{{- if ne $service "traefik" }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $service | lower }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $service | lower }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $service | lower }}
    spec:
      containers:
        - name: {{ $service | lower }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          ports:
            - containerPort: {{ $config.port }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-config
            - secretRef:
                name: {{ $.Release.Name }}-secret
{{- end }}
{{- end }}
{{- end }}