apiVersion: v1
kind: Secret
metadata:
  name: gen-ai-secret
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  OLLAMA_EMBED_KEY: {{ .Values.ollama.llmKey | b64enc }}
  OLLAMA_LLM_KEY: {{ .Values.ollama.llmKey | b64enc }}