{{- if .Values.services.ollama.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ollama
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ollama
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.services.ollama.image.repository }}:{{ .Values.services.ollama.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.services.ollama.port }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ollama
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-ollama
  ports:
    - port: {{ .Values.services.ollama.port }}
      targetPort: {{ .Values.services.ollama.port }}
  type: ClusterIP
{{- end }} 