# coding: utf-8

# flake8: noqa
"""
    DevOps Closed AI Server API

    API documentation for the DevOps Closed AI Server

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.add_task_dto import AddTaskDto
from openapi_client.models.create_project_dto import CreateProjectDto
from openapi_client.models.create_user_dto import CreateUserDto
from openapi_client.models.project_dto import ProjectDto
from openapi_client.models.task_dto import TaskDto
from openapi_client.models.task_status import TaskStatus
from openapi_client.models.user_dto import UserDto
