name: Linting Workflow

on: [push]

jobs:
  lint-client:
    name: Lint Client Code with ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  lint-server:
    name: Check Server Code with Spotless
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [project, task, user]
    defaults:
      run:
        working-directory: server/${{ matrix.service }}-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Run Spotless Check
        run: ../gradlew spotlessCheck

  lint-genai:
    name: Check GenAI Code with Black
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Black
        run: pip install black
      - name: Run Black Check
        run: black --check .
