name: Test Project

on: [push]

jobs:
  test-server:
    name: Run Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle and Check Coverage
        run: cd server && ./gradlew test jacocoTestCoverageVerification -x spotlessCheck -x spotlessApply

      - name: Generate JaCoCo Reports
        if: always()
        run: cd server && ./gradlew jacocoTestReport

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            server/user-service/build/reports/jacoco/
            server/project-service/build/reports/jacoco/
            server/task-service/build/reports/jacoco/
            server/common/build/reports/jacoco/

  test-genai:
    name: Run GenAI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: cd genai && pip install -r requirements.txt

      - name: Run tests with coverage
        run: cd genai && python -m pytest

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: genai/htmlcov/
