name: Test Project

on: [push]

jobs:
  test-server:
    name: Run Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: cd server && ./gradlew test

  test-genai:
    name: Run GenAI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: cd genai && pip install -r requirements.txt

      - name: Run tests with coverage
        run: cd genai && python -m pytest
