name: Test Project

on: [push]

jobs:
  test-server:
    name: Run Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle and Check Coverage
        run: cd server && ./gradlew check

      - name: Generate JaCoCo Reports
        if: always()
        run: cd server && ./gradlew jacocoTestReport

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            server/user-service/build/reports/jacoco/
            server/project-service/build/reports/jacoco/
            server/task-service/build/reports/jacoco/

# server/common/build/reports/jacoco/ TODO: Add tests
